profi/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from profi.settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static

from user_profile.views import UserListView
from .views import DashboardView


urlpatterns = [
    re_path(r'^jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('cabinet/', include([
        path('user/', include('user_profile.urls')),
        path('', DashboardView.as_view(), name='dashboard'),
    ])),
    path('documents/', include('documents.urls')),
    path('work/', include('work.urls')),
    path('privileges/', include('privileges.urls')),
    path('medicine/', include('medicine.urls')),
    path('dwelling/', include('dwelling.urls')),
    path('certificate/', include('certificate.urls')),
    # path('', DashboardView.as_view(), name='dashboard'),
    path('', UserListView.as_view(), name='users'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

user_profile/urls.py
from django.urls import path, include, re_path
from .views import (
    AuthView,
    user_logout,
    UserListView,
    # UserDetailView,
    NewUserView,
    # new_user,
    user_detail_view,
    NoteCreateView,
    ContactCreateView,
    LanguageCreateView,
    UserEditView,
    NoteUpdateView,
    ContactUpdateView,
    LanguageUpdateView,
    ContactDeleteView,
    LanguageDeleteView,
    ContactTypeCreateView,
    LanguageTitleCreateView,
    LanguageLevelCreateView,
    PortraitCreateView, PortraitUpdateView, PortraitDeleteView)


app_name = 'user'
urlpatterns = [
    path('login/', AuthView.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),
    path('users/', UserListView.as_view(), name='users'),
    path('new/', NewUserView.as_view(), name='new-user'),
    re_path(r'^note_create/(?P<pk>\d+)$', NoteCreateView.as_view(), name='note-create'),
    re_path(r'^contact_create/(?P<pk>\d+)$', ContactCreateView.as_view(), name='contact-create'),
    re_path(r'^contact_type_create/(?P<pk>\d+)$', ContactTypeCreateView.as_view(), name='contact-type-create'),
    re_path(r'^language_create/(?P<pk>\d+)$', LanguageCreateView.as_view(), name='language-create'),
    re_path(r'^portrait_create/(?P<pk>\d+)$', PortraitCreateView.as_view(), name='portrait-create'),
    re_path(r'^language_title_create/(?P<pk>\d+)$', LanguageTitleCreateView.as_view(), name='language-title-create'),
    re_path(r'^language_level_create/(?P<pk>\d+)$', LanguageLevelCreateView.as_view(), name='language-level-create'),
    re_path(r'^note_update/(?P<pk>\d+)$', NoteUpdateView.as_view(), name='note-update'),
    re_path(r'^contact_update/(?P<pk>\d+)-(?P<count>\d+)$', ContactUpdateView.as_view(), name='contact-update'),
    re_path(r'^language_update/(?P<pk>\d+)-(?P<count>\d+)$', LanguageUpdateView.as_view(), name='language-update'),
    re_path(r'^portrait_update/(?P<pk>\d+)-(?P<count>\d+)$', PortraitUpdateView.as_view(), name='portrait-update'),
    # re_path(r'^note_update/(?P<pk>\d+)$', NoteUpdateView.as_view(), name='note-update'),
    re_path(r'^contact_delete/(?P<pk>\d+)-(?P<count>\d+)$', ContactDeleteView.as_view(), name='contact-delete'),
    re_path(r'^language_delete/(?P<pk>\d+)-(?P<count>\d+)$', LanguageDeleteView.as_view(), name='language-delete'),
    re_path(r'^portrait_delete/(?P<pk>\d+)-(?P<count>\d+)$', PortraitDeleteView.as_view(), name='portrait-delete'),
    re_path(r'^user_edit/(?P<pk>\d+)$', UserEditView.as_view(), name='user-edit'),
    # path('new/', new_user, name='new-user'),
    # re_path(r'^(?P<pk>\d+)$', UserDetailView.as_view(), name='user-detail'),
    re_path(r'^(?P<pk>\d+)$', user_detail_view, name='user-detail'),
    # path('new_user/', UserListView.as_view(), name='new_user'),
]

work/urls.py
from django.urls import path, include, re_path
from .views import (
    DismissalCreateView, AssignmentCreateView, AdoptionCreateView,
    TransferCreateView, PermissionCreateView, VnosokCreateView,
    VocationCreateView, ControlCreateView, PrognosisCreateView,
    DisappearanceCreateView, DisappearanceUpdateView, PrognosisUpdateView,
    ControlUpdateView, VocationUpdateView, PermissionUpdateView,
    TransferUpdateView, AdoptionUpdateView, AssignmentUpdateView,
    DismissalUpdateView, DisappearanceDeleteView, PrognosisDeleteView,
    ControlDeleteView, VocationDeleteView, PermissionDeleteView,
    TransferDeleteView, AdoptionDeleteView, AssignmentDeleteView,
    DismissalDeleteView,
    VoivodshipCreateView, EmployerCreateView, FactoryCreateView)


app_name = 'work'
urlpatterns = [
    re_path(r'^create_dismissal/(?P<pk>\d+)$', DismissalCreateView.as_view(), name='create_dismissal'),
    re_path(r'^create_assignment/(?P<pk>\d+)$', AssignmentCreateView.as_view(), name='create_assignment'),
    re_path(r'^create_adoption/(?P<pk>\d+)$', AdoptionCreateView.as_view(), name='create_adoption'),
    re_path(r'^create_transfer/(?P<pk>\d+)$', TransferCreateView.as_view(), name='create_transfer'),
    re_path(r'^create_permission/(?P<pk>\d+)$', PermissionCreateView.as_view(), name='create_permission'),
    # re_path(r'^create_vnosok_list/(?P<pk>\d+)$', VnosokCreateView.as_view(), name='create_vnosok_list'),
    re_path(r'^create_vocation/(?P<pk>\d+)$', VocationCreateView.as_view(), name='create_vocation'),
    re_path(r'^create_incoming_control/(?P<pk>\d+)$', ControlCreateView.as_view(), name='create_incoming_control'),
    re_path(r'^create_prognosis/(?P<pk>\d+)$', PrognosisCreateView.as_view(), name='create_prognosis'),
    re_path(r'^create_voivodship/(?P<pk>\d+)$', VoivodshipCreateView.as_view(), name='create_voivodship'),
    re_path(r'^create_employer/(?P<pk>\d+)$', EmployerCreateView.as_view(), name='create_employer'),
    re_path(r'^create_factory/(?P<pk>\d+)$', FactoryCreateView.as_view(), name='create_factory'),
    re_path(r'^create_disappearance/(?P<pk>\d+)$', DisappearanceCreateView.as_view(), name='create_disappearance'),
    re_path(r'^update_dismissal/(?P<pk>\d+)-(?P<count>\d+)$', DismissalUpdateView.as_view(), name='update_dismissal'),
    re_path(r'^update_assignment/(?P<pk>\d+)-(?P<count>\d+)$', AssignmentUpdateView.as_view(), name='update_assignment'),
    re_path(r'^update_adoption/(?P<pk>\d+)-(?P<count>\d+)$', AdoptionUpdateView.as_view(), name='update_adoption'),
    re_path(r'^update_transfer/(?P<pk>\d+)-(?P<count>\d+)$', TransferUpdateView.as_view(), name='update_transfer'),
    re_path(r'^update_permission/(?P<pk>\d+)-(?P<count>\d+)$', PermissionUpdateView.as_view(), name='update_permission'),
    # re_path(r'^update_vnosok_list/(?P<pk>\d+)$', VnosokUpdateView.as_view(), name='update_vnosok_list'),
    re_path(r'^update_vocation/(?P<pk>\d+)-(?P<count>\d+)$', VocationUpdateView.as_view(), name='update_vocation'),
    re_path(r'^update_incoming_control/(?P<pk>\d+)-(?P<count>\d+)$', ControlUpdateView.as_view(), name='update_incoming_control'),
    re_path(r'^update_prognosis/(?P<pk>\d+)-(?P<count>\d+)$', PrognosisUpdateView.as_view(), name='update_prognosis'),
    re_path(r'^update_disappearance/(?P<pk>\d+)-(?P<count>\d+)$', DisappearanceUpdateView.as_view(), name='update_disappearance'),
    re_path(r'^delete_dismissal/(?P<pk>\d+)-(?P<count>\d+)$', DismissalDeleteView.as_view(), name='delete_dismissal'),
    re_path(r'^delete_assignment/(?P<pk>\d+)-(?P<count>\d+)$', AssignmentDeleteView.as_view(),
            name='delete_assignment'),
    re_path(r'^delete_adoption/(?P<pk>\d+)-(?P<count>\d+)$', AdoptionDeleteView.as_view(), name='delete_adoption'),
    re_path(r'^delete_transfer/(?P<pk>\d+)-(?P<count>\d+)$', TransferDeleteView.as_view(), name='delete_transfer'),
    re_path(r'^delete_permission/(?P<pk>\d+)-(?P<count>\d+)$', PermissionDeleteView.as_view(), name='delete_permission'),
    # re_path(r'^delete_vnosok_list/(?P<pk>\d+)$', VnosokDeleteView.as_view(), name='delete_vnosok_list'),
    re_path(r'^delete_vocation/(?P<pk>\d+)-(?P<count>\d+)$', VocationDeleteView.as_view(), name='delete_vocation'),
    re_path(r'^delete_incoming_control/(?P<pk>\d+)-(?P<count>\d+)$', ControlDeleteView.as_view(),
            name='delete_incoming_control'),
    re_path(r'^delete_prognosis/(?P<pk>\d+)-(?P<count>\d+)$', PrognosisDeleteView.as_view(), name='delete_prognosis'),
    re_path(r'^delete_disappearance/(?P<pk>\d+)-(?P<count>\d+)$', DisappearanceDeleteView.as_view(),
            name='delete_disappearance'),
]

user_profile/forms.py
from django import forms
from django.forms import Form
from django.utils.translation import ugettext_lazy as _
from django.core import validators
from .models import User, Language, Contact, ContactType, LanguageLevel, LanguageTitle, PsychologicalPortrait
from django.contrib.auth.hashers import check_password


names_validator = validators.RegexValidator('^[a-zA-Zа-яА-Я]+$', message=_(
        'Допускаются только латинские и кирилические символы нижнего и верхнего регистра'
    ))

phone_validator = validators.RegexValidator('^[0-9]+')
password_validator = validators.MinLengthValidator(10)


# class ForgotPasswordForm(Form):
#     """
#     Форма востановления пароля
#     """
#
#     error_css_class = 'is-invalid'
#     errors_class = 'is-invalid'
#
#     email = forms.EmailField(label=_('Email'), widget=forms.TextInput(
#         attrs={'class': 'form-control'},
#     ), validators=[validators.EmailValidator])
#
#     def clean_email(self):
#         email = self.cleaned_data.get('email')
#         if User.objects.filter(email__contains=email).exists():
#             return email
#         raise forms.ValidationError(_('Такой адрес електронной почты не используется'))


class AuthForm(Form):
    email = forms.CharField(widget=forms.TextInput(
        attrs={'class': 'form-control', 'type': 'email',
               'placeholder': _('Email')}), validators=[validators.EmailValidator])
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={'class': 'form-control', 'placeholder': _('Password')}))


class NewUserForm(forms.ModelForm):
    # polygon = forms.CharField(widget=forms.TextInput)

    class Meta:
        model = User
        fields = (
            'email',
            'first_name',
            'last_name',
            'patronymic',
        )


class NoteCreateForm(forms.ModelForm):
    # polygon = forms.CharField(widget=forms.TextInput)

    class Meta:
        model = User
        fields = (
            'note',
        )

    # def __init__(self, pk, *args, **kwargs):
    #     super(NoteCreateForm, self).__init__(*args, **kwargs)
    #     user = User.objects.get(pk=pk)
    #     self.fields['note'].initial = user.note

    # def get_initial_for_field(self, field, field_name):
    #     user = User.objects.get(pk=kwargs.pop('pk'))


class ContactCreateForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = (
            'type',
            'contact',
        )


class PortraitCreateForm(forms.ModelForm):

    class Meta:
        model = PsychologicalPortrait
        fields = (
            'intelligence',
            'professionalism',
            'self_discipline',
            'sociability',
            'temperament',
            'personality_type',
        )


class LanguageCreateForm(forms.ModelForm):

    class Meta:
        model = Language
        fields = (
            'title',
            'level',
        )


class ContactTypeCreateForm(forms.ModelForm):

    class Meta:
        model = ContactType
        fields = (
            'title',
        )


class LanguageTitleCreateForm(forms.ModelForm):

    class Meta:
        model = LanguageTitle
        fields = (
            'title',
        )


class LanguageLevelCreateForm(forms.ModelForm):

    class Meta:
        model = LanguageLevel
        fields = (
            'title',
        )


class UserEditForm(forms.ModelForm):
    # polygon = forms.CharField(widget=forms.TextInput)
    date_of_birth = forms.DateField(widget=forms.DateInput(format='%Y-%m-%d'),
                                    input_formats=('%Y-%m-%d',),
                                    required=False)

    class Meta:
        model = User
        fields = (
            'avatar',
            'email',
            'first_name',
            'last_name',
            'patronymic',
            'position',
            'status',
            'date_of_birth',
            'registration',
            'residence_address',
        )

    def __init__(self, pk, *args, **kwargs):
        super(UserEditForm, self).__init__(*args, **kwargs)
        user = User.objects.get(pk=pk)
        self.fields['avatar'].initial = user.avatar
        self.fields['email'].initial = user.email
        self.fields['first_name'].initial = user.first_name
        self.fields['last_name'].initial = user.last_name
        self.fields['position'].initial = user.position
        self.fields['patronymic'].initial = user.patronymic
        self.fields['status'].initial = user.status
        self.fields['date_of_birth'].initial = user.date_of_birth
        self.fields['registration'].initial = user.registration
        self.fields['residence_address'].initial = user.residence_address


class NoteUpdateForm(forms.ModelForm):

    class Meta:
        model = User
        fields = (
            'note',
        )


class ContactUpdateForm(forms.ModelForm):

    class Meta:
        model = Contact
        fields = (
            'type',
            'contact',
        )

    # def __init__(self, pk, *args, **kwargs):
    #     super(ContactUpdateForm, self).__init__(*args, **kwargs)
    #     user = User.objects.get(pk=pk)
    #     contact = user.contacts.first()
    #     # print('-' * 80)
    #     # print(contact)
    #     # print('-' * 80)
    #     if contact:
    #         self.fields['type'].initial = contact.type
    #         self.fields['contact'].initial = contact.contact


class LanguageUpdateForm(forms.ModelForm):

    class Meta:
        model = Language
        fields = (
            'title',
            'level',
        )

    # def __init__(self, pk, *args, **kwargs):
    #     super(LanguageUpdateForm, self).__init__(*args, **kwargs)
    #     user = User.objects.get(pk=pk)
    #     language = user.languages.first()
    #     if language:
    #         self.fields['title'].initial = language.title
    #         self.fields['level'].initial = language.level


class PortraitUpdateForm(forms.ModelForm):

    class Meta:
        model = PsychologicalPortrait
        fields = (
            'intelligence',
            'professionalism',
            'self_discipline',
            'sociability',
            'temperament',
            'personality_type',
        )

user_profile/templates/user_profile/add_user.html
{% extends 'cabinet-base.html' %}

{% block content %}
    <div class="row">
        <div class="col-6 m-auto">
            <div class="card">
                <div class="card-body">
                    <form method="post">
                        {% csrf_token %}
                        {% include 'includes/form.html' %}
                        <button type="submit" class="btn btn-success">Post</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

user_profile/templates/user_profile/authentication-signin.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>PROFI Dashboard</title>
    <!--favicon-->
    <link rel="icon" href="{% static 'cabinet/' %}assets/images/favicon.ico" type="image/x-icon">
    <!-- Bootstrap core CSS-->
    <link href="{% static 'cabinet/' %}assets/css/bootstrap.min.css" rel="stylesheet"/>
    <!-- animate CSS-->
    <link href="{% static 'cabinet/' %}assets/css/animate.css" rel="stylesheet" type="text/css"/>
    <!-- Icons CSS-->
    <link href="{% static 'cabinet/' %}assets/css/icons.css" rel="stylesheet" type="text/css"/>
    <!-- Custom Style-->
    <link href="{% static 'cabinet/' %}assets/css/app-style.css" rel="stylesheet"/>

</head>

<body class="authentication-bg">
<!-- Start wrapper-->
<div id="wrapper">
    <div class="card card-authentication1 mx-auto my-5 animated zoomIn">
        <div class="card-body">
            <div class="card-content p-2">
                <div class="text-center">
                    <img src="{% static 'cabinet/' %}assets/images/logo_profi.png"/>
                </div>
                <div class="card-title text-uppercase text-center py-2">Sign In</div>
                <div class="card-title text-uppercase text-center py-2">{{ user }}</div>
                <form method="post">
                    {% csrf_token %}

                    {% for field in form %}
                        <div class="form-group">
                            <div class="position-relative has-icon-left">
                                <label for="{{ field.id_for_label }}" class="sr-only-">{{ field.name }}</label>
                                {{ field }}
                            </div>
                        </div>
                    {% endfor %}


                    <div class="form-group">
                        <button type="submit" class="btn btn-danger shadow-danger btn-block waves-effect waves-light">
                            Ввійти
                        </button>
                    </div>
                    <div class="form-group text-center">
                        <p class="text-muted">Новий користувач? <a href="authentication-signup.html"> Зареєструватись</a></p>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!--Start Back To Top Button-->
    <a href="javaScript:void();" class="back-to-top"><i class="fa fa-angle-double-up"></i> </a>
    <!--End Back To Top Button-->
</div><!--wrapper-->

<!-- Bootstrap core JavaScript-->
<script src="{% static 'cabinet/' %}assets/js/jquery.min.js"></script>
<script src="{% static 'cabinet/' %}assets/js/popper.min.js"></script>
<script src="{% static 'cabinet/' %}assets/js/bootstrap.min.js"></script>
<!-- waves effect js -->
<script src="{% static 'cabinet/' %}assets/js/waves.js"></script>
<!-- Custom scripts -->
<script src="{% static 'cabinet/' %}assets/js/app-script.js"></script>

</body>
</html>

user_profile/templates/user_profile/users-list.html
{% extends 'cabinet-base.html' %}

{% block content %}
    <div class="row">
        <div class="col-lg-12">
          <div class="card">
            <div class="card-body">
              <a href="{% url 'user:new-user' %}" class="btn btn-outline-primary waves-effect waves-light m-3" style="float: right">Додати працівника</a>
            <br>
              <div class="table-responsive">
              <table id="example" class="table table-bordered">
                <thead>
                    <tr>
                        <th>ПІБ</th>
                        <th>Телефон</th>
                        <th>Завод</th>
                        <th>Спеціальність</th>
                        <th>Дата закінчення візи</th>
                        <th>Дата закінчення <br>дозволу на роботу</th>
                        <th>Статус</th>
                    </tr>
                </thead>
                <tbody>
                    {% for user in users %}
                       <tr>
                           <td><a href="{% url 'user:user-detail' user.id %}">{{ user.first_name }} {{ user.last_name }} {{ user.patronymic }}</a></td>
                           <td>{{ user.contacts.all|first|default:"не введено" }}</td>
                           <td>{{ user.permissions.last.factory|default:"не введено" }}</td>
                           <td>{{ user.position|default:"не введено" }}</td>
                           <td>{{ user.visas.last.expire|default:"не введено" }}</td>
                           <td>{{ user.permissions.last.expire|default:"не введено" }}</td>
                           <td>{{ user.status|default:"не введено" }}</td>
                       </tr>
                    {% endfor %}
                </tbody>
                <tfoot>
                    <tr>
                        <th>ПІБ</th>
                        <th>Телефон</th>
                        <th>Завод</th>
                        <th>Спеціальність</th>
                        <th>Дата закінчення візи</th>
                        <th>Дата закінчення <br>дозволу на роботу</th>
                        <th>Статус</th>
                    </tr>
                </tfoot>
            </table>
            </div>
            </div>
          </div>
        </div>
      </div><!-- End Row-->
{% endblock content %}