profi/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from profi.settings import MEDIA_ROOT, MEDIA_URL
from django.conf.urls.static import static

from user_profile.views import UserListView
from .views import DashboardView


urlpatterns = [
    re_path(r'^jet/', include('jet.urls', 'jet')),
    path('admin/', admin.site.urls),
    path('cabinet/', include([
        path('user/', include('user_profile.urls')),
        path('', DashboardView.as_view(), name='dashboard'),
    ])),
    path('documents/', include('documents.urls')),
    path('work/', include('work.urls')),
    path('privileges/', include('privileges.urls')),
    path('medicine/', include('medicine.urls')),
    path('dwelling/', include('dwelling.urls')),
    path('certificate/', include('certificate.urls')),
    # path('', DashboardView.as_view(), name='dashboard'),
    path('', UserListView.as_view(), name='users'),
] + static(MEDIA_URL, document_root=MEDIA_ROOT)

user_profile/urls.py
from django.urls import path, include, re_path
from .views import (
    AuthView,
    user_logout,
    UserListView,
    # UserDetailView,
    NewUserView,
    # new_user,
    user_detail_view,
    NoteCreateView,
    ContactCreateView,
    LanguageCreateView,
    UserEditView,
    NoteUpdateView,
    ContactUpdateView,
    LanguageUpdateView,
    ContactDeleteView,
    LanguageDeleteView,
    ContactTypeCreateView,
    LanguageTitleCreateView,
    LanguageLevelCreateView,
    PortraitCreateView, PortraitUpdateView, PortraitDeleteView)


app_name = 'user'
urlpatterns = [
    path('login/', AuthView.as_view(), name='login'),
    path('logout/', user_logout, name='logout'),
    path('users/', UserListView.as_view(), name='users'),
    path('new/', NewUserView.as_view(), name='new-user'),
    re_path(r'^note_create/(?P<pk>\d+)$', NoteCreateView.as_view(), name='note-create'),
    re_path(r'^contact_create/(?P<pk>\d+)$', ContactCreateView.as_view(), name='contact-create'),
    re_path(r'^contact_type_create/(?P<pk>\d+)$', ContactTypeCreateView.as_view(), name='contact-type-create'),
    re_path(r'^language_create/(?P<pk>\d+)$', LanguageCreateView.as_view(), name='language-create'),
    re_path(r'^portrait_create/(?P<pk>\d+)$', PortraitCreateView.as_view(), name='portrait-create'),
    re_path(r'^language_title_create/(?P<pk>\d+)$', LanguageTitleCreateView.as_view(), name='language-title-create'),
    re_path(r'^language_level_create/(?P<pk>\d+)$', LanguageLevelCreateView.as_view(), name='language-level-create'),
    re_path(r'^note_update/(?P<pk>\d+)$', NoteUpdateView.as_view(), name='note-update'),
    re_path(r'^contact_update/(?P<pk>\d+)-(?P<count>\d+)$', ContactUpdateView.as_view(), name='contact-update'),
    re_path(r'^language_update/(?P<pk>\d+)-(?P<count>\d+)$', LanguageUpdateView.as_view(), name='language-update'),
    re_path(r'^portrait_update/(?P<pk>\d+)-(?P<count>\d+)$', PortraitUpdateView.as_view(), name='portrait-update'),
    # re_path(r'^note_update/(?P<pk>\d+)$', NoteUpdateView.as_view(), name='note-update'),
    re_path(r'^contact_delete/(?P<pk>\d+)-(?P<count>\d+)$', ContactDeleteView.as_view(), name='contact-delete'),
    re_path(r'^language_delete/(?P<pk>\d+)-(?P<count>\d+)$', LanguageDeleteView.as_view(), name='language-delete'),
    re_path(r'^portrait_delete/(?P<pk>\d+)-(?P<count>\d+)$', PortraitDeleteView.as_view(), name='portrait-delete'),
    re_path(r'^user_edit/(?P<pk>\d+)$', UserEditView.as_view(), name='user-edit'),
    # path('new/', new_user, name='new-user'),
    # re_path(r'^(?P<pk>\d+)$', UserDetailView.as_view(), name='user-detail'),
    re_path(r'^(?P<pk>\d+)$', user_detail_view, name='user-detail'),
    # path('new_user/', UserListView.as_view(), name='new_user'),
]

work/urls.py
from django.urls import path, include, re_path
from .views import (
    DismissalCreateView, AssignmentCreateView, AdoptionCreateView,
    TransferCreateView, PermissionCreateView, VnosokCreateView,
    VocationCreateView, ControlCreateView, PrognosisCreateView,
    DisappearanceCreateView, DisappearanceUpdateView, PrognosisUpdateView,
    ControlUpdateView, VocationUpdateView, PermissionUpdateView,
    TransferUpdateView, AdoptionUpdateView, AssignmentUpdateView,
    DismissalUpdateView, DisappearanceDeleteView, PrognosisDeleteView,
    ControlDeleteView, VocationDeleteView, PermissionDeleteView,
    TransferDeleteView, AdoptionDeleteView, AssignmentDeleteView,
    DismissalDeleteView,
    VoivodshipCreateView, EmployerCreateView, FactoryCreateView)


app_name = 'work'
urlpatterns = [
    re_path(r'^create_dismissal/(?P<pk>\d+)$', DismissalCreateView.as_view(), name='create_dismissal'),
    re_path(r'^create_assignment/(?P<pk>\d+)$', AssignmentCreateView.as_view(), name='create_assignment'),
    re_path(r'^create_adoption/(?P<pk>\d+)$', AdoptionCreateView.as_view(), name='create_adoption'),
    re_path(r'^create_transfer/(?P<pk>\d+)$', TransferCreateView.as_view(), name='create_transfer'),
    re_path(r'^create_permission/(?P<pk>\d+)$', PermissionCreateView.as_view(), name='create_permission'),
    # re_path(r'^create_vnosok_list/(?P<pk>\d+)$', VnosokCreateView.as_view(), name='create_vnosok_list'),
    re_path(r'^create_vocation/(?P<pk>\d+)$', VocationCreateView.as_view(), name='create_vocation'),
    re_path(r'^create_incoming_control/(?P<pk>\d+)$', ControlCreateView.as_view(), name='create_incoming_control'),
    re_path(r'^create_prognosis/(?P<pk>\d+)$', PrognosisCreateView.as_view(), name='create_prognosis'),
    re_path(r'^create_voivodship/(?P<pk>\d+)$', VoivodshipCreateView.as_view(), name='create_voivodship'),
    re_path(r'^create_employer/(?P<pk>\d+)$', EmployerCreateView.as_view(), name='create_employer'),
    re_path(r'^create_factory/(?P<pk>\d+)$', FactoryCreateView.as_view(), name='create_factory'),
    re_path(r'^create_disappearance/(?P<pk>\d+)$', DisappearanceCreateView.as_view(), name='create_disappearance'),
    re_path(r'^update_dismissal/(?P<pk>\d+)-(?P<count>\d+)$', DismissalUpdateView.as_view(), name='update_dismissal'),
    re_path(r'^update_assignment/(?P<pk>\d+)-(?P<count>\d+)$', AssignmentUpdateView.as_view(), name='update_assignment'),
    re_path(r'^update_adoption/(?P<pk>\d+)-(?P<count>\d+)$', AdoptionUpdateView.as_view(), name='update_adoption'),
    re_path(r'^update_transfer/(?P<pk>\d+)-(?P<count>\d+)$', TransferUpdateView.as_view(), name='update_transfer'),
    re_path(r'^update_permission/(?P<pk>\d+)-(?P<count>\d+)$', PermissionUpdateView.as_view(), name='update_permission'),
    # re_path(r'^update_vnosok_list/(?P<pk>\d+)$', VnosokUpdateView.as_view(), name='update_vnosok_list'),
    re_path(r'^update_vocation/(?P<pk>\d+)-(?P<count>\d+)$', VocationUpdateView.as_view(), name='update_vocation'),
    re_path(r'^update_incoming_control/(?P<pk>\d+)-(?P<count>\d+)$', ControlUpdateView.as_view(), name='update_incoming_control'),
    re_path(r'^update_prognosis/(?P<pk>\d+)-(?P<count>\d+)$', PrognosisUpdateView.as_view(), name='update_prognosis'),
    re_path(r'^update_disappearance/(?P<pk>\d+)-(?P<count>\d+)$', DisappearanceUpdateView.as_view(), name='update_disappearance'),
    re_path(r'^delete_dismissal/(?P<pk>\d+)-(?P<count>\d+)$', DismissalDeleteView.as_view(), name='delete_dismissal'),
    re_path(r'^delete_assignment/(?P<pk>\d+)-(?P<count>\d+)$', AssignmentDeleteView.as_view(),
            name='delete_assignment'),
    re_path(r'^delete_adoption/(?P<pk>\d+)-(?P<count>\d+)$', AdoptionDeleteView.as_view(), name='delete_adoption'),
    re_path(r'^delete_transfer/(?P<pk>\d+)-(?P<count>\d+)$', TransferDeleteView.as_view(), name='delete_transfer'),
    re_path(r'^delete_permission/(?P<pk>\d+)-(?P<count>\d+)$', PermissionDeleteView.as_view(), name='delete_permission'),
    # re_path(r'^delete_vnosok_list/(?P<pk>\d+)$', VnosokDeleteView.as_view(), name='delete_vnosok_list'),
    re_path(r'^delete_vocation/(?P<pk>\d+)-(?P<count>\d+)$', VocationDeleteView.as_view(), name='delete_vocation'),
    re_path(r'^delete_incoming_control/(?P<pk>\d+)-(?P<count>\d+)$', ControlDeleteView.as_view(),
            name='delete_incoming_control'),
    re_path(r'^delete_prognosis/(?P<pk>\d+)-(?P<count>\d+)$', PrognosisDeleteView.as_view(), name='delete_prognosis'),
    re_path(r'^delete_disappearance/(?P<pk>\d+)-(?P<count>\d+)$', DisappearanceDeleteView.as_view(),
            name='delete_disappearance'),
]

templates/partials/_left-sidebar.html
{% load static %}

<div id="sidebar-wrapper" data-simplebar="" data-simplebar-auto-hide="true">
    <div class="brand-logo">
        <a href="{% url 'users' %}">
            <img src="{% static 'cabinet/' %}assets/images/logo_profi.png" class="logo-icon" alt="logo icon">
            <h5 class="logo-text">&#171;PROFI&#187;</h5>
        </a>
    </div>
    <div class="user-details">
        <div class="media align-items-center user-pointer collapsed" data-toggle="collapse"
             data-target="#user-dropdown">
            <div class="avatar">
            {% if user.avatar %}
            <img class="mr-3 side-user-img"
                                     src="{{ user.avatar.url }}"
                                     alt="user_avatar"/>
            {% else %}
            <img class="mr-3 side-user-img"
                                     src="{% static 'cabinet/' %}assets/images/avatars/avatar-1.png"
                                     alt="user_avatar"/>
            {% endif %}
            </div>
            <div class="media-body">
                <h6 class="side-user-name">{{ request.user.get_full_name|truncatechars:14 }}</h6>
            </div>
        </div>
        <div id="user-dropdown" class="collapse">
            <ul class="user-setting-menu">
                <li><a href="{% url 'user:logout' %}"><i class="icon-power"></i>Выйти</a></li>
            </ul>
        </div>
    </div>
    <ul class="sidebar-menu do-nicescrol">
        <li class="sidebar-header">Головне меню</li>
        <li><a href="{% url 'user:users' %}" class="waves-effect"><i class="icon-user"></i><span>Працівники</span></a>
        </li>
        <li><a href="{% url 'dashboard' %}" class="waves-effect"><i class="icon-doc"></i><span>Звіти</span></a>
        </li>
{#        <li>#}
{#            <a href="javaScript:void();" class="waves-effect">#}
{#                <i class="icon-calendar"></i><span>Multilevel</span>#}
{#                <i class="fa fa-angle-left pull-right"></i>#}
{#            </a>#}
{#            <ul class="sidebar-submenu">#}
{#                <li><a href="javaScript:void();"><i class="fa fa-long-arrow-right"></i> Level One</a></li>#}
{#                <li>#}
{#                    <a href="javaScript:void();"><i class="fa fa-long-arrow-right"></i> Level One <i#}
{#                            class="fa fa-angle-left pull-right"></i></a>#}
{#                    <ul class="sidebar-submenu">#}
{#                        <li><a href="javaScript:void();"><i class="fa fa-long-arrow-right"></i> Level Two</a></li>#}
{#                        <li>#}
{#                            <a href="javaScript:void();"><i class="fa fa-long-arrow-right"></i> Level Two <i#}
{#                                    class="fa fa-angle-left pull-right"></i></a>#}
{#                            <ul class="sidebar-submenu">#}
{#                                <li><a href="javaScript:void();"><i class="fa fa-long-arrow-right"></i> Level Three</a>#}
{#                                </li>#}
{#                                <li><a href="javaScript:void();"><i class="fa fa-long-arrow-right"></i> Level Three</a>#}
{#                                </li>#}
{#                            </ul>#}
{#                        </li>#}
{#                    </ul>#}
{#                </li>#}
{#                <li><a href="javaScript:void();" class="waves-effect"><i class="fa fa-long-arrow-right"></i> Level#}
{#                    One</a></li>#}
{#            </ul>#}
{#        </li>#}
    </ul>

</div>

templates/partials/_topbar.html
{% load static %}

    <header class="topbar-nav">
        <nav class="navbar navbar-expand fixed-top bg-primary">
            <ul class="navbar-nav mr-auto align-items-center">
                <li class="nav-item">
                    <a class="nav-link toggle-menu" href="javascript:void();">
                        <i class="icon-menu menu-icon"></i>
                    </a>
                </li>
{#                <li class="nav-item">#}
{#                    <form class="search-bar">#}
{#                        <input type="text" class="form-control" placeholder="Enter keywords">#}
{#                        <a href="javascript:void();"><i class="icon-magnifier"></i></a>#}
{#                    </form>#}
{#                </li>#}
            </ul>

            <ul class="navbar-nav align-items-center right-nav-link">
{#                <li class="nav-item dropdown-lg">#}
{#                    <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown"#}
{#                       href="javascript:void();">#}
{#                        <i class="icon-envelope-open"></i></a>#}
{#                    <div class="dropdown-menu dropdown-menu-right animated fadeIn">#}
{#                        <ul class="list-group list-group-flush">#}
{#                            <li class="list-group-item d-flex justify-content-between align-items-center">#}
{#                                You have 4 new messages#}
{#                                <span class="badge badge-danger">4</span>#}
{#                            </li>#}
{#                            <li class="list-group-item">#}
{#                                <a href="javaScript:void();">#}
{#                                    <div class="media">#}
{#                                        <div class="avatar"><img class="align-self-start mr-3"#}
{#                                                                 src="{% static 'cabinet/' %}assets/images/avatars/avatar-1.png"#}
{#                                                                 alt="user avatar"></div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="mt-0 msg-title">Jhon Deo</h6>#}
{#                                            <p class="msg-info">Lorem ipsum dolor sit amet...</p>#}
{#                                            <small>Today, 4:10 PM</small>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li class="list-group-item">#}
{#                                <a href="javaScript:void();">#}
{#                                    <div class="media">#}
{#                                        <div class="avatar"><img class="align-self-start mr-3"#}
{#                                                                 src="{% static 'cabinet/' %}assets/images/avatars/avatar-2.png"#}
{#                                                                 alt="user avatar"></div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="mt-0 msg-title">Sara Jen</h6>#}
{#                                            <p class="msg-info">Lorem ipsum dolor sit amet...</p>#}
{#                                            <small>Yesterday, 8:30 AM</small>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li class="list-group-item">#}
{#                                <a href="javaScript:void();">#}
{#                                    <div class="media">#}
{#                                        <div class="avatar"><img class="align-self-start mr-3"#}
{#                                                                 src="{% static 'cabinet/' %}assets/images/avatars/avatar-3.png"#}
{#                                                                 alt="user avatar"></div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="mt-0 msg-title">Dannish Josh</h6>#}
{#                                            <p class="msg-info">Lorem ipsum dolor sit amet...</p>#}
{#                                            <small>5/11/2018, 5:50 PM</small>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li class="list-group-item">#}
{#                                <a href="javaScript:void();">#}
{#                                    <div class="media">#}
{#                                        <div class="avatar"><img class="align-self-start mr-3"#}
{#                                                                 src="{% static 'cabinet/' %}assets/images/avatars/avatar-4.png"#}
{#                                                                 alt="user avatar"></div>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="mt-0 msg-title">Katrina Mccoy</h6>#}
{#                                            <p class="msg-info">Lorem ipsum dolor sit amet.</p>#}
{#                                            <small>1/11/2018, 5:50 PM</small>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li class="list-group-item"><a href="javaScript:void();">See All Messages</a></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </li>#}
{#                <li class="nav-item dropdown-lg">#}
{#                    <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown"#}
{#                       href="javascript:void();">#}
{#                        <i class="icon-bell"></i><span class="badge badge-primary badge-up">10</span></a>#}
{#                    <div class="dropdown-menu dropdown-menu-right animated fadeIn">#}
{#                        <ul class="list-group list-group-flush">#}
{#                            <li class="list-group-item d-flex justify-content-between align-items-center">#}
{#                                You have 10 Notifications#}
{#                                <span class="badge badge-primary">10</span>#}
{#                            </li>#}
{#                            <li class="list-group-item">#}
{#                                <a href="javaScript:void();">#}
{#                                    <div class="media">#}
{#                                        <i class="icon-people fa-2x mr-3 text-info"></i>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="mt-0 msg-title">New Registered Users</h6>#}
{#                                            <p class="msg-info">Lorem ipsum dolor sit amet...</p>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li class="list-group-item">#}
{#                                <a href="javaScript:void();">#}
{#                                    <div class="media">#}
{#                                        <i class="icon-cup fa-2x mr-3 text-warning"></i>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="mt-0 msg-title">New Received Orders</h6>#}
{#                                            <p class="msg-info">Lorem ipsum dolor sit amet...</p>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li class="list-group-item">#}
{#                                <a href="javaScript:void();">#}
{#                                    <div class="media">#}
{#                                        <i class="icon-bell fa-2x mr-3 text-danger"></i>#}
{#                                        <div class="media-body">#}
{#                                            <h6 class="mt-0 msg-title">New Updates</h6>#}
{#                                            <p class="msg-info">Lorem ipsum dolor sit amet...</p>#}
{#                                        </div>#}
{#                                    </div>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li class="list-group-item"><a href="javaScript:void();">See All Notifications</a></li>#}
{#                        </ul>#}
{#                    </div>#}
{#                </li>#}
{#                <li class="nav-item language">#}
{#                    <a class="nav-link dropdown-toggle dropdown-toggle-nocaret waves-effect" data-toggle="dropdown"#}
{#                       href="pages-blank-page.html#"><i class="flag-icon flag-icon-gb"></i></a>#}
{#                    <ul class="dropdown-menu dropdown-menu-right animated fadeIn">#}
{#                        <li class="dropdown-item"><i class="flag-icon flag-icon-gb mr-5"></i> English</li>#}
{#                        <li class="dropdown-item"><i class="flag-icon flag-icon-fr mr-5"></i> French</li>#}
{#                        <li class="dropdown-item"><i class="flag-icon flag-icon-cn mr-2"></i> Chinese</li>#}
{#                        <li class="dropdown-item"><i class="flag-icon flag-icon-de mr-2"></i> German</li>#}
{#                    </ul>#}
{#                </li>#}
                <li class="nav-item">
                    <a class="nav-link dropdown-toggle dropdown-toggle-nocaret" data-toggle="dropdown"
                       href="pages-blank-page.html#">
                        <span class="user-profile"><img src="{% static 'cabinet/' %}assets/images/avatars/avatar-1.png"
                                                        class="img-circle" alt="user avatar"></span>
                    </a>
                    <ul class="dropdown-menu dropdown-menu-right animated fadeIn">
                        <li class="dropdown-item user-details">
                            <a href="javaScript:void();">
                                <div class="media">
                                    <div class="avatar">
                                             {% if user.avatar %}
                                            <img class="align-self-start mr-3"
                                                                     src="{{ user.avatar.url }}"
                                                                     alt="user_avatar"/>
                                            {% else %}
                                            <img class="align-self-start mr-3"
                                                                     src="{% static 'cabinet/' %}assets/images/avatars/avatar-1.png"
                                                                     alt="user_avatar"/>
                                            {% endif %}
                                    <div class="media-body">
                                        <h6 class="mt-2 user-title">{{ request.user.last_name }} {{ request.user.first_name }}</h6>
                                        <p class="user-subtitle">{{ request.user.email }}</p>
                                    </div>
                                </div>
                            </a>
                        </li>
                        <li class="dropdown-divider"></li>
                        <li class="dropdown-item"><a href="{% url 'user:user-detail' request.user.id %}"><i class="icon-wallet mr-2"></i> Особистий кабінет</li>
                        <li class="dropdown-divider"></li>
                        <li class="dropdown-item"><a href="{% url 'user:logout' %}"><i class="icon-power mr-2"></i> Вийти</a></li>
                    </ul>
                </li>
            </ul>
        </nav>
    </header>